#!/bin/sh

if [ "$1" == '-o' ] ; then
	echo 'Using home profile...'
	sh_profile=bash_profile_home
else
	echo 'Using work profile...'
	sh_profile=bash_profile_work
fi

echo 'Creating bash profile link...'
ln -sv "${PWD}/${sh_profile}" "${HOME}/.bash_profile"
exit_code=$?

echo 'Creating vimrc link...'
ln -sv "${PWD}/vimrc" "${HOME}/.vimrc"
if [ $exit_code -eq 0 ] ; then exit_code=$? ; fi

echo 'Creating Sublime Text preference links...'
for sublsetting in SublimeText/*.sublime-settings ; do
	ln -sv "${PWD}/$sublsetting" "${HOME}/Library/Application Support/Sublime Text 3/Packages/User"
	if [ $exit_code -eq 0 ] ; then exit_code=$? ; fi
done

exit $exit_code
